version: '3.5'

services:
  tesla_trip_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tesla_trip_api
    image: tesla-trip-api
    volumes:
      - ./src:/app:rw
      - ~/tesla_trip_api/image:/app/static/image
    env_file: .env
    networks:
      - tesla-trip-proxy
    ports:
      - "5000:5000"
    tty: true

networks:
  tesla-trip-proxy:
    external:
      name: tesla-trip-network

